# Generated by Django 3.2.12 on 2022-02-22 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('collection_method', models.CharField(choices=[('01', 'Scraping'), ('02', 'Manual'), ('03', 'Upload'), ('04', 'API')], max_length=2)),
                ('amt_relay', models.CharField(max_length=100)),
                ('group', models.GenericIPAddressField()),
                ('source', models.GenericIPAddressField()),
                ('udp_port', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('report_count', models.IntegerField(default=0)),
                ('source_name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_description_set', to='view.stream')),
                ('user_submitted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
