# Generated by Django 4.0.4 on 2022-06-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_auto_20220405_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='stream_previews/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='stream',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='stream_previews/%Y/%m/%d/'),
        ),
    ]
