# Generated by Django 4.0.4 on 2022-06-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_stream_preview_stream_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='stream_previews/%Y/%m/%d/%H'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='stream_previews/%Y/%m/%d/%H'),
        ),
    ]
