# Generated by Django 3.2.15 on 2022-08-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0013_tunnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnel',
            name='active_viewer_count',
            field=models.IntegerField(default=1),
        ),
    ]
