# Generated by Django 3.2.8 on 2021-10-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('looking_glass', models.CharField(choices=[('I2', 'Internet2'), ('GEANT', 'GEANT')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whois', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('udp_port', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(max_length=50)),
                ('pps', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_found', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('downvote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10000)),
                ('votes', models.IntegerField(default=0)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.stream')),
            ],
        ),
    ]
