# Generated by Django 3.2.5 on 2022-01-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='amt_gateway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='owner_description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='owner_whois',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='submission_method',
            field=models.CharField(choices=[('1', 'Scraping'), ('2', 'Manual Report'), ('3', 'File Submission')], default='1', max_length=5),
            preserve_default=False,
        ),
    ]
