# Generated by Django 3.2.12 on 2022-04-05 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='amt_relay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='collection_method',
            field=models.CharField(blank=True, choices=[('01', 'Scraping'), ('02', 'Manual'), ('03', 'Upload'), ('04', 'API')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='group',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stream',
            name='source',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='udp_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
