# Generated by Django 4.0.4 on 2022-07-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='categories',
            field=models.ManyToManyField(to='view.category'),
        ),
    ]
