# Generated by Django 4.0.4 on 2022-07-10 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0008_stream_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stream',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
