# Generated by Django 4.0.4 on 2022-07-25 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('view', '0011_alter_trendingstream_options_stream_removed_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='categories',
            field=models.ManyToManyField(blank=True, to='view.category'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_streams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stream',
            name='removed_likes',
            field=models.ManyToManyField(blank=True, related_name='unliked_streams', to=settings.AUTH_USER_MODEL),
        ),
    ]
