# Generated by Django 3.2.15 on 2022-08-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0014_alter_tunnel_active_viewer_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tunnel',
            name='filename',
        ),
    ]
