# Generated by Django 3.2.15 on 2022-09-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0015_remove_tunnel_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnel',
            name='amt_gateway_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
