# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='last_found',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
