# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_stream_last_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='last_found',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
