# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-28 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200428_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='pps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
