# Generated by Django 3.0.6 on 2020-05-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200428_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
