# Generated by Django 3.0.6 on 2020-09-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_stream_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
    ]
