# Generated by Django 3.0.6 on 2021-04-23 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_stream_udp_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='group',
            field=models.CharField(max_length=50, validators=[django.core.validators.validate_ipv4_address]),
        ),
        migrations.AlterField(
            model_name='stream',
            name='source',
            field=models.CharField(max_length=50, validators=[django.core.validators.validate_ipv4_address]),
        ),
        migrations.AlterField(
            model_name='stream',
            name='udp_port',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.validate_integer]),
        ),
    ]
