# Generated by Django 3.0.6 on 2021-04-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210423_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_source',
            name='looking_glass',
            field=models.CharField(choices=[('I2', 'Internet2'), ('GEANT', 'GEANT')], default='I2', max_length=10),
            preserve_default=False,
        ),
    ]
