# Generated by Django 3.2.8 on 2021-11-17 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_submitted', models.DateTimeField(auto_now_add=True)),
                ('path_to_uploaded_file', models.CharField(blank=True, max_length=100)),
                ('url_to_streamed_video', models.URLField(blank=True, null=True)),
                ('celery_task_id', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_submission_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManualReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_submitted', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('udp_port', models.CharField(max_length=50)),
                ('celery_task_id', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_report_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
