# Generated by Django 3.2.8 on 2021-11-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0002_streamsubmission_task_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_failed', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
    ]
