# Generated by Django 3.2.5 on 2022-01-19 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_auto_20220119_0449'),
        ('add', '0003_failedquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualreport',
            name='amt_gateway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manualreport',
            name='owner_description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='manualreport',
            name='owner_whois',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manualreport',
            name='stream',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='view.stream'),
        ),
        migrations.AddField(
            model_name='streamsubmission',
            name='stream',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='view.stream'),
        ),
    ]
