# Generated by Django 3.2.5 on 2022-01-19 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('add', '0004_auto_20220119_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualreport',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_report_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
