# Generated by Django 3.2.5 on 2022-01-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0005_alter_manualreport_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualreport',
            name='error_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
