# Generated by Django 3.2.12 on 2022-04-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0005_alter_uploadsubmission_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsubmission',
            name='uploaded_file',
            field=models.CharField(max_length=100),
        ),
    ]
