# Generated by Django 3.2.12 on 2022-04-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0006_alter_uploadsubmission_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsubmission',
            name='stream_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
