# Generated by Django 3.2.12 on 2022-02-22 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=40)),
                ('allowed_inside', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UploadSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
                ('celery_id', models.IntegerField()),
                ('stream_pid', models.IntegerField()),
                ('access_code', models.CharField(max_length=40)),
                ('uploaded_file', models.CharField(max_length=40)),
                ('matched', models.BooleanField(default=False)),
                ('stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='view.stream')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scraping', to='view.stream')),
            ],
        ),
        migrations.CreateModel(
            name='ManualSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
                ('celery_id', models.IntegerField()),
                ('error_msg', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual', to='view.stream')),
            ],
        ),
        migrations.CreateModel(
            name='APISubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('access_code', models.CharField(max_length=40)),
                ('stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api', to='view.stream')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add.translator')),
            ],
        ),
    ]
