# Generated by Django 3.2.12 on 2022-04-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualsubmission',
            name='celery_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
