# Generated by Django 3.2.12 on 2022-04-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0004_auto_20220409_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsubmission',
            name='access_code',
            field=models.CharField(max_length=100),
        ),
    ]
